version: 2

updates:
  package-ecosystem: npm
  directory: '/'
  schedule:
    interval: 'weekly'
    day: 'wednesday'
    time: '06:00'
    timezone: 'Europe/Zurich'
  target-branch: 'dev'
  versioning-strategy: 'increase'
