name: deploy

on:
  - workflow_call
  - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy documentation website
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_BASE: '.'
          NETLIFY_CMD: npm run build
          NETLIFY_DIR: packages/docs/.vuepress/dist
