name: release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump'
        required: false
      preid:
        description: 'Pre-version ID'
        required: true
        default: 'beta'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Set Git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: npm ci
      - run: npx lerna version ${{ github.event.inputs.bump }} --conventional-commits --create-release github --yes --preid ${{ github.event.inputs.preid }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npx lerna publish from-git --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
