name: "size"
on:
  pull_request:
    branches:
      - master
jobs:
  size:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/chusho
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: andresz1/size-limit-action@v1.2.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}